### ISSUE TITLE
Opinions from salt core team

### ISSUE THREAD

**Issue by yagnik** [yagnik/salt-template#1]
This is the only way to get your attention to this repo. 
I have been using this to setup salt in production system and wanted to get your opinions on it along with the asking if you think we should put it in docs and/or move to salt org to help new devs to get easily on boarded on salt?

@cachedout @thatch45 @s0undt3ch

**Comment by thatch45** [comment]
Sorry I have not been able to get back to you on this front. We have all been swamped with getting the Nitrogen release out.
We have a few ways to get people on-boarded in Salt and while I think that you have a great setup here I think that we would need to do more research on the options before we made a shift in the core docs or before we took in another repo to maintain on the salt org.

**Comment by yagnik** [comment]
@thatch45 thanks makes sense to me :)
